### ISSUE TITLE
need help from @jaseknighter

### ISSUE THREAD

**Issue by tyleretters** [northern-information/cci#3]
https://github.com/northern-information/cci/blob/099bdb70e05808d4b27e8a63984322f2c5191efe/lib/graphics.lua#L90-L102

@jaseknighter !

**Comment by jaseknighter** [comment]
fixed with checkin "lsystem fixes (issue 3)" and making the following changes:

* simplify code
* remove lsys_renderer.lua
* turn lsys_controller into a class
* set x,y,scale with parameters built into lsys_controller's setup function (replacing TRBL stuff)

@tyleretters, please close if you are happy with the fixes.

**Comment by tyleretters** [comment]
thank you so much @jaseknighter !
