### ISSUE TITLE
sampler bug

### ISSUE THREAD

**Issue by tyleretters** [northern-information/cci#5]
hey @schollz! i was hoping could help debug this little one, please?

# steps to reproduce

1. pull [28f5bab](https://github.com/northern-information/cci/commit/28f5babd49f680683627472a2bd5eae3cb39fa7b).
2. start the script.
3. press k2 or k3.

# expected behavior

- k2: `/wav/ui-down.wav` plays once.
- k3: `/wav/ui-up.wav` plays once.

# actual behavior

- the sample plays looped
- additionally, the "first in" sample plays. so if k2 is pressed first, pressing k3 plays the k2 same sample.

**Comment by schollz** [comment]
oops I meant to make a PR but it looks like I have write access so I just committed the fix....

> the "first in" sample plays

this is fixed! I was setting the `bufnum` to the filename! so SuperCollider for some reason didn't fail and just loaded some random buffer whenever it was playing (maybe buffer 0, which is the first-in buffer) which is why it seemed like it worked before without me catching it.

> the sample plays looped

this didn't happen for me...do you mean it plays looped infinitely? or just once? I noticed that the key triggering the sound was on up *and* down presses, so that would make the sound play twice - but this is because of `function key`. I may need another reproduction instructions to get this error

**Comment by tyleretters** [comment]
thank you so much!

> do you mean it plays looped infinitely?

yes. i'll see if it is still happening. (the sound would play twice because i don't have the ol' `if z == 0 then return end` in there. any time i'd press the key it would loop infinitely so i didn't notice the keyup.
